# Generated by Django 5.1.4 on 2025-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(default='Unknown', max_length=50)),
                ('manufacturer', models.CharField(default='Unknown', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('serial_number', models.CharField(default='Unknown', max_length=50, unique=True)),
                ('location', models.CharField(default='Unknown', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
            ],
        ),
    ]
