# Generated by Django 5.1.4 on 2025-01-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_preventive_maintenance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Medical_device_inventory',
        ),
    ]
