# Generated by Django 4.2.5 on 2025-06-26 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item", "0004_rename_item_medical_device_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceAlarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=1000,
                        verbose_name="Alarm Message / Maintenance Required",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrective_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="item.corrective_maintenance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="item.medical_device_inventory",
                    ),
                ),
                (
                    "preventive_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="item.preventive_maintenance",
                    ),
                ),
            ],
        ),
    ]
